# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/bin/cmake/bin/cmake

# The command to remove a file.
RM = /opt/clion/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/liushan/mylab/clang/grid_sort

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/liushan/mylab/clang/grid_sort

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liushan/mylab/clang/grid_sort/CMakeFiles /home/liushan/mylab/clang/grid_sort/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liushan/mylab/clang/grid_sort/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named grid_sort

# Build rule for target.
grid_sort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grid_sort
.PHONY : grid_sort

# fast build rule for target.
grid_sort/fast:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/build
.PHONY : grid_sort/fast

ctl_lsn.o: ctl_lsn.c.o

.PHONY : ctl_lsn.o

# target to build an object file
ctl_lsn.c.o:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/ctl_lsn.c.o
.PHONY : ctl_lsn.c.o

ctl_lsn.i: ctl_lsn.c.i

.PHONY : ctl_lsn.i

# target to preprocess a source file
ctl_lsn.c.i:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/ctl_lsn.c.i
.PHONY : ctl_lsn.c.i

ctl_lsn.s: ctl_lsn.c.s

.PHONY : ctl_lsn.s

# target to generate assembly for a file
ctl_lsn.c.s:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/ctl_lsn.c.s
.PHONY : ctl_lsn.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/main.c.s
.PHONY : main.c.s

read.o: read.c.o

.PHONY : read.o

# target to build an object file
read.c.o:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/read.c.o
.PHONY : read.c.o

read.i: read.c.i

.PHONY : read.i

# target to preprocess a source file
read.c.i:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/read.c.i
.PHONY : read.c.i

read.s: read.c.s

.PHONY : read.s

# target to generate assembly for a file
read.c.s:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/read.c.s
.PHONY : read.c.s

sort_file/bubble_sort.o: sort_file/bubble_sort.c.o

.PHONY : sort_file/bubble_sort.o

# target to build an object file
sort_file/bubble_sort.c.o:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sort_file/bubble_sort.c.o
.PHONY : sort_file/bubble_sort.c.o

sort_file/bubble_sort.i: sort_file/bubble_sort.c.i

.PHONY : sort_file/bubble_sort.i

# target to preprocess a source file
sort_file/bubble_sort.c.i:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sort_file/bubble_sort.c.i
.PHONY : sort_file/bubble_sort.c.i

sort_file/bubble_sort.s: sort_file/bubble_sort.c.s

.PHONY : sort_file/bubble_sort.s

# target to generate assembly for a file
sort_file/bubble_sort.c.s:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sort_file/bubble_sort.c.s
.PHONY : sort_file/bubble_sort.c.s

sort_file/sort_file.o: sort_file/sort_file.c.o

.PHONY : sort_file/sort_file.o

# target to build an object file
sort_file/sort_file.c.o:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sort_file/sort_file.c.o
.PHONY : sort_file/sort_file.c.o

sort_file/sort_file.i: sort_file/sort_file.c.i

.PHONY : sort_file/sort_file.i

# target to preprocess a source file
sort_file/sort_file.c.i:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sort_file/sort_file.c.i
.PHONY : sort_file/sort_file.c.i

sort_file/sort_file.s: sort_file/sort_file.c.s

.PHONY : sort_file/sort_file.s

# target to generate assembly for a file
sort_file/sort_file.c.s:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sort_file/sort_file.c.s
.PHONY : sort_file/sort_file.c.s

start_srv_master.o: start_srv_master.c.o

.PHONY : start_srv_master.o

# target to build an object file
start_srv_master.c.o:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/start_srv_master.c.o
.PHONY : start_srv_master.c.o

start_srv_master.i: start_srv_master.c.i

.PHONY : start_srv_master.i

# target to preprocess a source file
start_srv_master.c.i:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/start_srv_master.c.i
.PHONY : start_srv_master.c.i

start_srv_master.s: start_srv_master.c.s

.PHONY : start_srv_master.s

# target to generate assembly for a file
start_srv_master.c.s:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/start_srv_master.c.s
.PHONY : start_srv_master.c.s

start_srv_node.o: start_srv_node.c.o

.PHONY : start_srv_node.o

# target to build an object file
start_srv_node.c.o:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/start_srv_node.c.o
.PHONY : start_srv_node.c.o

start_srv_node.i: start_srv_node.c.i

.PHONY : start_srv_node.i

# target to preprocess a source file
start_srv_node.c.i:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/start_srv_node.c.i
.PHONY : start_srv_node.c.i

start_srv_node.s: start_srv_node.c.s

.PHONY : start_srv_node.s

# target to generate assembly for a file
start_srv_node.c.s:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/start_srv_node.c.s
.PHONY : start_srv_node.c.s

sub_func/get_file_line_num.o: sub_func/get_file_line_num.c.o

.PHONY : sub_func/get_file_line_num.o

# target to build an object file
sub_func/get_file_line_num.c.o:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sub_func/get_file_line_num.c.o
.PHONY : sub_func/get_file_line_num.c.o

sub_func/get_file_line_num.i: sub_func/get_file_line_num.c.i

.PHONY : sub_func/get_file_line_num.i

# target to preprocess a source file
sub_func/get_file_line_num.c.i:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sub_func/get_file_line_num.c.i
.PHONY : sub_func/get_file_line_num.c.i

sub_func/get_file_line_num.s: sub_func/get_file_line_num.c.s

.PHONY : sub_func/get_file_line_num.s

# target to generate assembly for a file
sub_func/get_file_line_num.c.s:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sub_func/get_file_line_num.c.s
.PHONY : sub_func/get_file_line_num.c.s

sub_func/get_last_char.o: sub_func/get_last_char.c.o

.PHONY : sub_func/get_last_char.o

# target to build an object file
sub_func/get_last_char.c.o:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sub_func/get_last_char.c.o
.PHONY : sub_func/get_last_char.c.o

sub_func/get_last_char.i: sub_func/get_last_char.c.i

.PHONY : sub_func/get_last_char.i

# target to preprocess a source file
sub_func/get_last_char.c.i:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sub_func/get_last_char.c.i
.PHONY : sub_func/get_last_char.c.i

sub_func/get_last_char.s: sub_func/get_last_char.c.s

.PHONY : sub_func/get_last_char.s

# target to generate assembly for a file
sub_func/get_last_char.c.s:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sub_func/get_last_char.c.s
.PHONY : sub_func/get_last_char.c.s

sub_func/merge_file.o: sub_func/merge_file.c.o

.PHONY : sub_func/merge_file.o

# target to build an object file
sub_func/merge_file.c.o:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sub_func/merge_file.c.o
.PHONY : sub_func/merge_file.c.o

sub_func/merge_file.i: sub_func/merge_file.c.i

.PHONY : sub_func/merge_file.i

# target to preprocess a source file
sub_func/merge_file.c.i:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sub_func/merge_file.c.i
.PHONY : sub_func/merge_file.c.i

sub_func/merge_file.s: sub_func/merge_file.c.s

.PHONY : sub_func/merge_file.s

# target to generate assembly for a file
sub_func/merge_file.c.s:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/sub_func/merge_file.c.s
.PHONY : sub_func/merge_file.c.s

test.o: test.c.o

.PHONY : test.o

# target to build an object file
test.c.o:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/test.c.o
.PHONY : test.c.o

test.i: test.c.i

.PHONY : test.i

# target to preprocess a source file
test.c.i:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/test.c.i
.PHONY : test.c.i

test.s: test.c.s

.PHONY : test.s

# target to generate assembly for a file
test.c.s:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/test.c.s
.PHONY : test.c.s

write_log.o: write_log.c.o

.PHONY : write_log.o

# target to build an object file
write_log.c.o:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/write_log.c.o
.PHONY : write_log.c.o

write_log.i: write_log.c.i

.PHONY : write_log.i

# target to preprocess a source file
write_log.c.i:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/write_log.c.i
.PHONY : write_log.c.i

write_log.s: write_log.c.s

.PHONY : write_log.s

# target to generate assembly for a file
write_log.c.s:
	$(MAKE) -f CMakeFiles/grid_sort.dir/build.make CMakeFiles/grid_sort.dir/write_log.c.s
.PHONY : write_log.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... grid_sort"
	@echo "... ctl_lsn.o"
	@echo "... ctl_lsn.i"
	@echo "... ctl_lsn.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... read.o"
	@echo "... read.i"
	@echo "... read.s"
	@echo "... sort_file/bubble_sort.o"
	@echo "... sort_file/bubble_sort.i"
	@echo "... sort_file/bubble_sort.s"
	@echo "... sort_file/sort_file.o"
	@echo "... sort_file/sort_file.i"
	@echo "... sort_file/sort_file.s"
	@echo "... start_srv_master.o"
	@echo "... start_srv_master.i"
	@echo "... start_srv_master.s"
	@echo "... start_srv_node.o"
	@echo "... start_srv_node.i"
	@echo "... start_srv_node.s"
	@echo "... sub_func/get_file_line_num.o"
	@echo "... sub_func/get_file_line_num.i"
	@echo "... sub_func/get_file_line_num.s"
	@echo "... sub_func/get_last_char.o"
	@echo "... sub_func/get_last_char.i"
	@echo "... sub_func/get_last_char.s"
	@echo "... sub_func/merge_file.o"
	@echo "... sub_func/merge_file.i"
	@echo "... sub_func/merge_file.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... write_log.o"
	@echo "... write_log.i"
	@echo "... write_log.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

